### ISSUE TITLE
use parallel-stream?

### ISSUE THREAD

**Issue by ian29** [mapbox/trizilla#5]
i wonder if we shouldn't consider using https://github.com/rclark/parallel-stream

pro:
- nice framework for writing stream processors
- aysnc == speedup?

con: 
- will async stream processing ruin aggregation since parallel-stream only lets you process 1 chunk at a time but the aggregator needs 4 chunks to do it's thing

**Comment by ian29** [comment]
bah cc @rclark @dnomadb

**Comment by rclark** [comment]
If you want to use streams, then you are going to have to put some logic somewhere that aggregates "chunks" until you're sure that you have everything that you need to do an aggregation. 

Parallel-stream has a `_preprocess` function that you could feasibly use to aggregate a few chunks at a time, but you should only use parallel-stream if you're certain that async == speedup. Otherwise it'd probably be simpler to work with native stream objects.

**Comment by ian29** [comment]
not doin this
